In [1]:
import numpy as np

In [2]:
arr = np.array([[1,23,4],[2,45,45]])

In [3]:
arr.shape

(2, 3)

In [4]:
arr.ndim

2

In [5]:
arr[0].max()

23

In [6]:
arr.dtype

dtype('int32')

In [7]:
arr2 = np.arange(100)

In [8]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
np.__version__

'1.23.4'

## Slicing

In [10]:
arr[0:1]

array([[ 1, 23,  4]])

## Axis

In [11]:
arr2 = np.array([[10,23,45],[12,61,23]])

In [12]:
arr2.sum(axis=1) # Axis 1 sum all the elements according to the row

array([78, 96])

In [13]:
arr2.sum(axis=0) # Axis 0 sum all the elements according to the column

array([22, 84, 68])

In [14]:
arr2

array([[10, 23, 45],
       [12, 61, 23]])

In [15]:
arr2.transpose()

array([[10, 12],
       [23, 61],
       [45, 23]])

In [16]:
arr*arr2

array([[  10,  529,  180],
       [  24, 2745, 1035]])

## Sorting

In [17]:
np.sort(arr2)

array([[10, 23, 45],
       [12, 23, 61]])

## NumPy Array Iterating

In [18]:
for i in np.nditer(arr2): # np.nditer() used to iterate ndimentional array
    print(i)

10
23
45
12
61
23


## ndenumerate() 

In [19]:
for i in np.ndenumerate(arr2): # ndenumetrate funtion return every elements with their index number
    print(i)

((0, 0), 10)
((0, 1), 23)
((0, 2), 45)
((1, 0), 12)
((1, 1), 61)
((1, 2), 23)


## reshape

In [20]:
arr3 = np.array([10,3,34,45,5,6,45,5,45,4,54,5,4,4])

In [21]:
arr3.shape

(14,)

In [22]:
arr3 = arr3.reshape(2,7) # we can customize the dimension of any ndim 1 dim array

In [23]:
arr3

array([[10,  3, 34, 45,  5,  6, 45],
       [ 5, 45,  4, 54,  5,  4,  4]])

In [24]:
arr3.shape

(2, 7)

In [25]:
arr3.ndim

2

## Random

In [1]:
from numpy import random

In [9]:
random_number = random.randint(100)
random_number

70

In [12]:
random_number1 = random.rand()
random_number1

0.18238860001279433